addSbtPlugin("com.timushev.sbt"          % "sbt-updates"     % "0.4.0")
addSbtPlugin("io.get-coursier"           % "sbt-coursier"    % "1.1.0-M14-4")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"    % "0.1.6")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"    % "2.0.0")
addSbtPlugin("org.wartremover"           % "sbt-wartremover" % "2.4.2")
